#!/bin/bash

set -x  # All executed commands are printed to the terminal

aptitude update ; aptitude install -y letsencrypt nginx python-certbot-nginx

apt-get -y autoremove ; aptitude -y autoclean ; apt-get -y autoclean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.aptitude
